spring:
  datasource:
    url: jdbc:sqlserver://simash-sql.database.windows.net:1433;database=simash-sql-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Simash
    password: Happy123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


